#!/bin/bash
set -eu

ROOTDIR="$(dirname $(cd "$(dirname "$0")" && pwd))"
CFGFILE=$ROOTDIR/backup.cfg
HOSTNAME=$(hostname)
LOGFILE=$ROOTDIR/backup.log

# functions #############
error() {
  printf '\E[31m'; echo "$@"; printf '\E[0m' | tee -a $LOGFILE
}

log() {
  echo "$(date --rfc-3339=seconds): $@" | tee -a $LOGFILE
}

failure() {
  error "Execution failed!"
  exit -1
}

backup_dir() {
  TARGETPATH=$BACKUP_TARGET/$HOSTNAME/$1
  log "Backing up $1 to $TARGETPATH ..."
  PASSPHRASE=""  duplicity --encrypt-sign-key $GPG_KEY_ID $1 $TARGETPATH | tee -a $LOGFILE
}

backup_dirs(){
  for d in ${SOURCE_DIRS[@]}
  do
    backup_dir $d
  done

}

# main #################
trap failure EXIT

if [ ! -f $CFGFILE ] ; then
  error "Config files does not exist: $CFGFILE"
  failure
fi

log "Using config file: $CFGFILE"
. $CFGFILE


backup_dirs

log "Done."
trap '' EXIT


